id: PD0DA1DAC
initial_creation_type: input
source_metadata:
  title: Termas
  language: it
  description: 'A collection of spiritual treasures or terma (gter ma), which were
    reportedly hidden by Guru Padmasambhava and Yeshe Tsogyal, either in the earth
    and in the minds of disciples, and then revealed at the appropriate time by ‘treasure
    revealers’ or tertön (gter ston):'
  volume:
    27bc21c7365a4f3ea19799b6f38b8136:
      title: Daily Practice of Vajrakīla
      parent: Apang Tertön
    8cfcc6098d184875adec6ea7b8eb7621:
      title: 'The New Glorious Bestower of Immortality: A Long-Life Practice and Empowerment
        that Unites the Oral, Treasure and Visionary Teachings'
      parent: Chöje Lingpa
    4be835df4ef84dd2b18e64f52ed9e30f:
      title: The Sādhana and Empowerment for the Extremely Close Lineage of the Long-Life
        Practice that Unites the Oral, Treasure and Visionary Teachings
      parent: Chöje Lingpa
    502de9988f56440c9ed910e15380565a:
      title: The Aspiration of the Vajradhātu Maṇḍala
      parent: Chokgyur Dechen Lingpa
    2f414f2bd6c14dd6887f6517be45db4c:
      title: 'The Concise Cleansing Offering from The Guru’s Heart Practice: Dispelling
        All Obstacles on the Path'
      parent: Chokgyur Dechen Lingpa
    af2e4044722b41629976b69c294fed7f:
      title: The Lament of Rudra
      parent: Chokgyur Dechen Lingpa
    49211b000fb44a31b6ae0d66645f2a5c:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    a011edf1a9f44d91b670991fe7df131f:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    8694f8c97f2042efa74f5c7e6a47d227:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    f63c066f1d9743c7b40c43059ff10252:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    0511aaceb3764a56959cbf9baec185b2:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    9a578c28237f4ef1bee6a3f6ff6cad1d:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Chokgyur Dechen Lingpa
    f82530b186174679a4530924e38b0b89:
      title: Concise Daily Practice of Vajrasattva
      parent: Chokgyur Dechen Lingpa
    016e217f590b44638745787cbc22c83c:
      title: Concise Offering of the Body from the Root Text of the Heart Accomplishment
        of the Guru Tukdrup, The Essential Manual of Oral Instructions (Shaldam Nyingjang)
      parent: Chokgyur Dechen Lingpa
    b21df97f9273483595ab8170f2e9ab95:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    81ac76c64f4941838542dd3b717e20b1:
      title: Heart of Vajrasattva—The Heart of Confession, the King of Purification
        Practices, from 'The Immaculate Secret Vajrasattva'
      parent: Do Khyentse
    fd68d0e46a0e47448b68a72cdeed55ee:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    93f937f9c1ff440b80d4e3efb4c884c1:
      title: The Recitation for the Gradual Path of the Preliminaries from The Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī
      parent: Do Khyentse
    8d2aa99f652e42c592fb8f711b077509:
      title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly
        Secret, Enlightened Heart-Essence of the Ḍākinī'
      parent: Do Khyentse
    f015d1589db442be9c7c6747a778bad0:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    8ddbf184dd384d4bb4fdfccd834d3fc2:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Dorje Dechen Lingpa
    c7856a989c0648d3b9add8e2867abebe:
      title: The Biography of the Great Orgyen that Naturally Liberates On Sight
      parent: Dudjom Lingpa
    4a7127e09ba44fea96aa936979c1ebe7:
      title: A Concise Recitation of the Preliminary Practice according to the New
        Treasure of Dudjom
      parent: Dudjom Rinpoche
    9046921fb9ea49d08c8fdc314771d90a:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    a64885ad33044583a6197bdc83aaa5dd:
      title: 'Accomplishing the Lama through the Seven-Line Prayer: A Special Teaching
        from the Lama Sangdü'
      parent: Guru Chöwang
    4e5557cad7e7458f9e4a05fda89b1926:
      title: Ārya Mañjuśrī Tantra Garbha
      parent: Guru Chöwang
    bf6f7414dacd4000b395aa7902bba030:
      title: 'Emptying the Hells from their Very Depths: The Sovereign Practice for
        the Confession of all Impairments and Breakages of Vows and all Negative Actions
        and Obscurations'
      parent: Guru Chöwang
    dae40310755d47a08ed17303af71b4a3:
      title: 'Meeting the Buddha Face to Face: A Pith Instruction on Realizing the
        Fortress, Ravine, and View of the Practice of Vajrakīla'
      parent: Guru Chöwang
    7e3b0ee1ba38400d99e538cbdff7122f:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Guru Chöwang
    93e8f729a3c24052bc5ee3187f6d9eb3:
      title: 'The Brilliant Essence: The Ritual Manual for the Secret Embodiment of
        the Guru (Lama Sangdü)'
      parent: Guru Chöwang
    c2904be94dc2408a96077e8d63110be7:
      title: 'Vajrakīla Prayer: A Rain of Accomplishments'
      parent: Gyarong Khandro
    558f1a0dd2c542a8aafed9cc253bf10b:
      title: A Means to Pacify the Fear of Natural Disasters
      parent: Jamyang Khyentse Chökyi Lodrö
    bdaceea14c7b4cc4855021770bf86359:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    ec93fa2594de4f4a9990399f987cd03c:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Jamyang Khyentse Wangpo
    43f05649fc9f4ae1a1becc770627e2cd:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    191d3ab3ef134eaa857806e268f11642:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Jamyang Khyentse Wangpo
    1b49c0a4263e423baaf09caaeb6bf5ad:
      title: Maṇḍala Offering from the Tradition of Jatsön Nyingpo
      parent: Jatsön Nyingpo
    3b8ae031cb574a03b0cf899b1974a1a9:
      title: The Guidebook to the Hidden Land of Pemokö
      parent: Jatsön Nyingpo
    6a6996a0f0be4925bf137fa5ecc7f9cd:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Jigdral Tutop Lingpa
    dfd6ff8df724487cb7a86d77a024d18b:
      title: 'A Glimpse of the Crucial Points: The Vidyādhara''s Manual of Concealed
        Instructions'
      parent: Jigme Lingpa
    b515a25efb7f49e297af2e90ceefee13:
      title: A Glorious Garland of Great Bliss, the Root Sādhana of the Queen of Great
        Bliss, Yumka Tsogyal, from the Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    055c2215c17c4217b91c978cb250f599:
      title: A Ritual of Blessing and Empowerment for the Female Practice, from the
        Heart Essence of the Vast Expanse
      parent: Jigme Lingpa
    8fd56ec1aae9414aba114142270893c8:
      title: A Sādhana of Hayagrīva’s Assembly, from the Heart-Essence of the Vast
        Expanse
      parent: Jigme Lingpa
    84f311255fb644e1b19770f7853e129f:
      title: Awesome Ones’ Assembly (Palchen Düpa), the Heart Practice of the Awareness-Holders
      parent: Jigme Lingpa
    6b59096e50ab4d2e916aa923e0f08847:
      title: Brief Prayer of the Feast Gathering
      parent: Jigme Lingpa
    b33aca29a75e47eeb0317b42189c304c:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    f7ef8afb415c47f58d31338bb63d764f:
      title: 'Skull Fragments: The Root Tantra of the Vidyādharas'
      parent: Jigme Lingpa
    acebe810f31845bbbe4789e11c490850:
      title: 'The Continuous Shower of Blessings: A Prayer to the Lineage of the Great
        Perfection’s Heart-Essence of the Vast Expanse (Dzogpachenpo Longchen Nyingtik)'
      parent: Jigme Lingpa
    19469fd325d84f0a88a878d56ee40b3e:
      title: The History of the Female Practice of the Queen of Great Bliss
      parent: Jigme Lingpa
    0742095b5a0249dbaa0823ae08ee83e4:
      title: The Prayer of the Ground, Path & Fruition – From the Heart-Essence of
        the Vast Expanse
      parent: Jigme Lingpa
    a5f947569ec5481f849c4f39044d16dc:
      title: The Root Empowerment of the Vase Conferring Majesty from the Heart-Essence
        of the Vast Expanse
      parent: Jigme Lingpa
    07db84fccf4a46cba7d765317cd0b9d6:
      title: The Secret Practice of the Great Compassionate One, Natural Liberation
        of Suffering
      parent: Jigme Lingpa
    de4d2c6bdc1a40d7bc5d373e71d4988c:
      title: The Spontaneous Vajra Song of Fulfilment and Confession
      parent: Jigme Lingpa
    0f0f6ad7d83242238a21f555d280edd7:
      title: 'The Treasury of the Four Activities: A Fire Offering to Yumka'
      parent: Jigme Lingpa
    05eccc3f5fca4d5c82e0d59307847466:
      title: 'The Vase of Immortal Life: The Long-Life Practice of the Vidyādharas,
        from the Heart Essence of the Vast Expanse'
      parent: Jigme Lingpa
    1fa0da5a09a945978341d5483ce673c0:
      title: The Vidyādhara Assembly (Rigdzin Düpa), the Inner Practice from the Heart
        Essence of the Vast Expanse
      parent: Jigme Lingpa
    dec2d0e767f14a468f4d9b5694c826d3:
      title: 'The Words of the Awesome Ones: A General Overview of the Three Yogas
        from the Heart-Essence of the Vast Expanse'
      parent: Jigme Lingpa
    759d4a1dcd2242f49dbfef1179751bd0:
      title: 'Transference: Enlightenment Without Meditation (root text)'
      parent: Jigme Lingpa
    db70cd8e3773495f840c0efbcbc128ab:
      title: Vajra Verses on the Natural State
      parent: Jigme Lingpa
    e819b2f8a2c448fbaca1e519a90c3918:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Karma Lingpa
    cb6db56bf0cc4bf5938c00ba4f162d9d:
      title: The Benefits of the Vajra Guru Mantra and an Explanation of Its Syllables
      parent: Karma Lingpa
    91515de77c764cfe8aca5ec1a5d9c9e2:
      title: The Root Verses on the Six Bardos
      parent: Karma Lingpa
    af20560bda754dc5bd5c6289e94bc431:
      title: A Sādhana of Kurukullā from the Tidro Dharma Cycle
      parent: Khenchen Jigme Phuntsok
    80f6243e50f543c690c22f8beeb3e961:
      title: 'Accomplishing All Activity: A Daily Practice of the Great and Glorious
        Dorje Drolö'
      parent: Khenchen Jigme Phuntsok
    283daf718afb4745b298f1eda87254a2:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Lhatsün Namkha Jigme
    8b878c2861d04211b0da05442f9fff5b:
      title: Maṇḍala Offering from Longsal Dorje Nyingpo
      parent: Longsal Nyingpo
    4efa5ada1ca54604983d0d54cc46dfec:
      title: 'Liberation Upon Hearing: The History of the Great Jarung Kashor Stūpa'
      parent: Ngakchang Shakya Zangpo
    3edb9bd6b8c142ecb548aa743857a542:
      title: The Sovereign of Confessions for all Impairments and Breakages, Extracted
        from the Rampant Elephant Tantra
      parent: Nyala Pema Dündul
    aa566616a8734c81bfd2cd67a92b9acc:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    2d38aa298b0943ba83d6da71a9ab710d:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    15055973805f4ba1b413bf376f66b987:
      title: The Pointing-the-Staff Instruction
      parent: Nyang Ral Nyima Özer
    b04331125dbd46be9e6c65e58541c160:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: Orgyen Lingpa
    2f70982899b94e2eae8b5b7ce8e49806:
      title: Yeshe Tsogyal's Prayer
      parent: Pema Lingpa
    45a894aaea3b46e3bf68181e1066a24e:
      title: Aspiration Prayer from Tārā Sādhana
      parent: Ratna Lingpa
    93992b4475a54969917d6dff214a5597:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Rigdzin Gödem
    fe0f063ff5f149e6906e8890e7313d5f:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Rigdzin Gödem
    1e59afcdfa884d5b918150e731aa72f6:
      title: 'Marmé Mönlam: The Light Offering Prayer'
      parent: Rigdzin Nyima Drakpa
    8503d0698b8645e6a687eead6476a0f1:
      title: A Prayer Recounting the Lives and Liberation of the Exalted Ḍākinī Mandāravā
      parent: Samten Lingpa
    4d236f15e47c4cc08e6349f96a9b620e:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sera Khandro
    9c778d28386b4175867a2e5f0a844253:
      title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the
        Reality Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
      parent: Sera Khandro
    fb40600adb8b476e8a465dfc17db86da:
      title: Dispeller of All Samaya Corruptions and Pollutions
      parent: Sherab Özer
    2283ecf2c07c43abb2919d2c1c5b43d0:
      title: Brief Sukhāvatī Aspiration
      parent: Tertön Mingyur Dorje
    a219f8e2c3234a7fab7313cb84c9eef3:
      title: Dedication from Vajravārāhī Cycle of Namchö revealed by Mingyur Dorje
      parent: Tertön Mingyur Dorje
    141aa08f7fe148a1ba0a1736aae88103:
      title: Prayer to Behold Amitābha in Dreams
      parent: Tertön Mingyur Dorje
    e8412ebe5ed540b7b146337caf132eac:
      title: 'Inventory: The Perfectly Clear Mirror from the Razor of the Innermost
        Essence'
      parent: Tertön Sogyal
    bc22962fae6c41888ce73a1ffe3725e8:
      title: Sādhana of Mañjughoṣa
      parent: Tertön Sogyal
    f8941f497bb2470fac2b733bf948d761:
      title: 'The Falling Rain of Blessings: A Prayer of Inspiration'
      parent: Tertön Sogyal
    d65a56c837484c9cb9307787e63c30af:
      title: The Guru Yoga of the Profound Path
      parent: Tertön Sogyal
    f4c24334eb804362afd99c101e32514e:
      title: The Method to Pacify All Epidemics, Illnesses and Pandemics from the
        Sixty Solitary Forms of Yamāntaka
      parent: Tertön Sogyal
    2aa20aec82c34f22b212dc48d4cfc0c8:
      title: The Summoning of Blessings which Brings them Swift and Fast
      parent: Tertön Sogyal
    0ff5517a61d94680a4ed9418da012b5e:
      title: 'The Swift Path to Great Bliss: A Sādhana of Amitābha, Buddha of Limitless
        Light'
      parent: Tertön Sogyal
    1351281717ce4468bcbe6748a525b229:
      title: The Wisdom Mind Practice of One Kīla
      parent: Tertön Sogyal
    cd5acdbe2be04a69b7347e0eeab75f53:
      title: 'Le''u Dünma—Chapter 1: The Prayer to the Three Kāya Guru'
      parent: Tulku Zangpo Drakpa
    fcc96a509d5a49cbbc705b8e4b35d63f:
      title: 'Le''u Dünma—Chapter 2: The Prayer Requested by King Tri Songdetsen'
      parent: Tulku Zangpo Drakpa
    3af55f957025400c9bfad82adae1a39b:
      title: 'Le''u Dünma—Chapter 3: The Prayer Requested by Khandro Yeshe Tsogyal'
      parent: Tulku Zangpo Drakpa
    60bca2629d03446fa1ba3ceaeec6b9e1:
      title: 'Le''u Dünma—Chapter 4: The Prayer Requested by Namkhe Nyingpo'
      parent: Tulku Zangpo Drakpa
    a52b33d549234f2fa10b9139506d8a5b:
      title: 'Le''u Dünma—Chapter 5: The Prayer Requested by Nanam Dorje Dudjom'
      parent: Tulku Zangpo Drakpa
    f95b74aae36f40628653c1a5c83b8b03:
      title: 'Le''u Dünma—Chapter 6: The Prayer Requested by Prince Mutri Tsenpo'
      parent: Tulku Zangpo Drakpa
    adf842251aec4cb39222ee24d4222b71:
      title: Le'u Dünma—Chapter 7. The Prayer to Guru Rinpoche that Spontaneously
        Fulfills All Wishes (Sampa Lhundrupma)
      parent: Tulku Zangpo Drakpa
    c89df4eedbd74f90802fd81e76a404e0:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Tulku Zangpo Drakpa
created_at: '2022-03-01T06:17:48.630998'
last_modified_at: '2022-03-01T06:17:48.631000'
